version: '3.8'
services:
  php-apache:
    build:
      context: ci/build
      dockerfile: php/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./ci/build/apache/myapp.conf:/etc/apache2/sites-enabled/myapp.conf
      - ./ci/build/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - database
      - cache

  cache:
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  cache:
    driver: local
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
